POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Bhanu",
  "email": "bhanu@gmail.com",
  "password": "password123"
}

#####

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "bhanu@gmail.com",
  "password": "password123"
}

####

POST http://localhost:3000/candidates/register
Content-Type: application/json

{
  "name": "Candidate A",
  "email": "candidateA@gmail.com",
  "party": "Party X",
  "password": "candidate123"
}


####
POST http://localhost:3000/candidates/login
Content-Type: application/json

{
  "email": "candidateA@gmail.com",
  "password": "candidate123"
}

####
GET http://localhost:3000/candidates
Authorization: Bearer {{voterToken}}

####
POST http://localhost:3000/vote/1
Authorization: Bearer {{voterToken}}


####
POST http://localhost:3000/vote/1
Authorization: Bearer {{voterToken}}


####
GET http://localhost:3000/candidates/me/votes
Authorization: Bearer {{candidateToken}}
